server:
  port: 8000

management:
  endpoints:
    web:
      exposure:
        include=*:
logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR
    root: warn

spring:
  jpa:
    show-sql: true
  datasource:
    DATABASE_URL: car-clinic.c7qmoioqshab.eu-north-1.rds.amazonaws.com:5432/car_clinic
    username: postgres
    password: KV2Wtug6yuZXYbOyU1Km
  hibernate:
    ddl-auto: update
  h2:
    console:
      enabled: true
  security:
    user:
      name: admin
      password: UqtPmP8duSd79^bq


