server:
  port: 8000

management:
  endpoints:
    web:
      exposure:
        include=*:
logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR
    root: warn

spring:
  jpa:
    show-sql: true
#  datasource:
#    url: jdbc:postgresql://127.0.0.1:5432/postgres
#    DATABASE_URL: postgres://u9qpts5k9ot20i:p3e46dd9ecc8158f1fa4eaae4f0975c0eea59b6fb9a458c79a8a476bf7e305023@ceu9lmqblp8t3q.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com:5432/dc8mqb3e7ftvvu
#    username: postgres
#    password: postgres
  hibernate:
    ddl-auto: update
  h2:
    console:
      enabled: true
  security:
    user:
      name: admin
      password: UqtPmP8duSd79^bq


